### ISSUE TITLE
Tokyo Azure Meetup

### ISSUE THREAD

**Issue by satoryu** [satonaoki/azurejp#1]
コミュニティに、Tokyo Azure Meetup を追加していただけないでしょうか？

http://www.meetup.com/Tokyo-Azure-Meetup/

**Comment by satonaoki** [comment]
Done.

https://github.com/satonaoki/azurejp/wiki/Community-(%E3%82%B3%E3%83%9F%E3%83%A5%E3%83%8B%E3%83%86%E3%82%A3)
